### ISSUE TITLE
2 documents 

### ISSUE THREAD

**Issue by aloshTM** [Heliodex/orchives#16]
https://docs.google.com/document/u/0/d/1rl4FKaD7tueSXgtEWvCUqGVXREg_aAGF7BMBLkrFHDg/mobilebasic

**Comment by Heliodex** [comment]
https://www.youtube.com/watch?v=23mknmBdW9g

**Comment by Heliodex** [comment]
hold on wait i didnt done it yet

**Comment by aloshTM** [comment]
oops

**Comment by aloshTM** [comment]
another 
https://docs.google.com/document/d/1i1IIRGIAKJpymCG554Y-5R3iyzs3cpV0g9FEE5fG7H4/edit?usp=sharing

**Comment by Heliodex** [comment]
Ok thanks!
