### ISSUE TITLE
about the samtheman expose doc

### ISSUE THREAD

**Issue by Phil564** [Heliodex/orchives#5]
he responded to the doc with a 10 minute video. https://www.youtube.com/watch?v=2dPxzuvyabY
most of the bs in the doc is outdated and aep is just doing this since he's mad at sam for taking down fossci's domain for a day

i don't think that this doc should be on the site, if you're adding shitty ass docs like that just add ficello's outdated ass aep doc lol

**Comment by Heliodex** [comment]
Thanks, added the video to the additions section at the bottom of the document
