### ISSUE TITLE
missing document

### ISSUE THREAD

**Issue by aloshTM** [Heliodex/orchives#8]
there was a document written by yeano that has been swept under the rug for whatever reason.

im pretty sure it was about the 608 situation way before it happened, basically accusations (?)

your gonna have to ask yeano for the document, because i only remember it exists and not the link

(if you found it, just know it has the "The Whole Shabang" tooken from the first document, also **i am not 100% sure the contents of the document**, i just remember it existing)

**Comment by aloshTM** [comment]
wait im an idiot the aep doc was already added.. Oops

**Comment by aloshTM** [comment]
it was posted in the testcore labs server by ficello originally but i dont ahve the discord invite and im pretty sure the message got deleted

**Comment by aloshTM** [comment]
ill close for now as i can't remember nothin

**Comment by Phil564** [comment]
oh and there wasn't even a google docs, it was just distributed as a pdf lol

**Comment by Heliodex** [comment]
> oh and there wasn't even a google docs, it was just distributed as a pdf lol

Ah okay, that's probably the full one that was listed in #4 then, thanks!
